# Generated by Django 4.2 on 2023-05-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic_education',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('que', models.CharField(max_length=1000)),
                ('ans', models.CharField(max_length=2000)),
            ],
        ),
    ]
