# Generated by Django 4.2 on 2023-05-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='electricity',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('que', models.CharField(max_length=1000)),
                ('ans', models.CharField(max_length=2000)),
            ],
        ),
    ]
