# Generated by Django 4.2 on 2023-05-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_electricity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='basic_education',
            new_name='information',
        ),
    ]
