# Generated by Django 4.2 on 2023-05-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_rename_basic_education_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jal_Jeevan_Mission',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('que', models.CharField(max_length=1000)),
                ('ans', models.CharField(max_length=2000)),
            ],
        ),
    ]
