# Generated by Django 4.1 on 2023-05-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_jal_jeevan_mission"),
    ]

    operations = [
        migrations.CreateModel(
            name="raised_questions",
            fields=[
                ("SNo", models.AutoField(primary_key=True, serialize=False)),
                ("que", models.CharField(max_length=1000)),
                ("dept", models.CharField(max_length=100)),
            ],
        ),
    ]
