# Generated by Django 4.2 on 2023-05-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_delete_education_delete_medical'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('que', models.CharField(max_length=1000)),
                ('ans', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('que', models.CharField(max_length=1000)),
                ('ans', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='medical',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('que', models.CharField(max_length=1000)),
                ('ans', models.CharField(max_length=2000)),
            ],
        ),
    ]
