# Generated by Django 4.2 on 2023-05-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_contact_education_medical'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='education',
        ),
        migrations.DeleteModel(
            name='medical',
        ),
    ]
